import type { Metadata } from "next";
import "./globals.css";
import { styled } from "../../styled-system/jsx";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const StyledBody = styled("body", {
  base: {
    fontFamily: "mono",
  },
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <StyledBody>{children}</StyledBody>
    </html>
  );
}
